name: Build client and prepare deploy branch

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Node.js version
        uses: actions/setup-node@main
        with:
          node-version: '18.x'

      - name: Install Dependencies for client application.
        working-directory: ./client
        run: npm install

      - name: Run Client Tests
        working-directory: ./client
        run: npm run test

      - name: Build client application.
        working-directory: ./client
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@main
        with:
          name: client
          path: ./client/build
          retention-days: 1

  prepare-deploy:
    runs-on: ubuntu-latest
    needs: build-client

    steps:
      - uses: actions/checkout@main

      - name: Download artifact from build job
        uses: actions/download-artifact@main
        with:
          name: client
          path: ./public

      - name: Remove .github folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./.github

      - name: Remove client folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./client

      - name: Remove .idea folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./.idea

      - name: Remove .vscode folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./.vscode

      - name: Remove .gitignore
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./.gitignore

      - name: Remove README.md
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./README.md

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@main
        with:
          name: server
          path: .

      - name: Configure git
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}

      - name: Create deploy branch
        run: git branch deploy

      - name: Checkout deploy branch
        run: git checkout deploy

      - name: Push to deploy branch
        run: |
          git add -A .
          git commit -m "${GITHUB_SHA::7} deployable created by CI workflow"
          git push origin deploy -f